print("Monday: Cloudy, High of 45, Low of 35")
print("Tuesday: Partly Cloudy High of 46, Low of 36")
print("Wednesday: Partly Cloudy High of 46, Low of 32")
print("Thursday: Scattered Showers, High of 45, Low of 22")
print("Friday: Cloudy, High of 31, Low of 22")
print("Saturday: Partly Cloudy, High of 43, Low of 35")
print("Sunday: Cloudy with a chance of rain, High of 47, Low of 36")